model:
  vocab_size: 50257
  context_length: 64
  emb_dim: 64
  n_heads: 4
  n_layers: 2
  drop_rate: 0.1
  qkv_bias: false
training:
  batch_size: 2
  stride: 32
  learning_rate: 0.0004
  weight_decay: 0.1
  epochs: 1
